name: Deploy with CloudFlare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies [1]
        run: npm install -g npm@10.2.2

      - name: Install dependencies [2]
        run: npm install --legacy-peer-deps

      - name: Build worker
        run: npm run build

      - name: Publish
        run: npm --version
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'julianarodrigues'
          directory: 'build'
          gitHubToken: ${{ secrets.TOKEN_GITHUB }}
          branch: main
          wranglerVersion: '3'